include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - pubspec*
    - "**/*.g.dart"
    - "**/*.mapper.dart"

  errors:
    one_member_abstracts: ignore
    public_member_api_docs: ignore
